### ISSUE TITLE
`AbstractArray` vector subtypes get wrongly handled

### ISSUE THREAD

**Issue by lkdvos** [Jutho/KrylovKit.jl#100]
It seems like whenever the custom vector-type is `<:AbstractArray`, and has `IndexLinear` indexing style, we eagerly assume that it can be treated as if it is an `Array`, taking [this path](https://github.com/Jutho/KrylovKit.jl/blob/1b175b7bd57a9535e26b738dbc7403ec30aee444/src/orthonormal.jl#L297) in the code for `basistransform!`. I think it would probably be more reasonable to have `<:DenseArray` or even just `<:Array` there, as we are no longer adhering to the `VectorInterface` set of allowed operations there.

For example, `similar` is being used instead of `zerovector` (https://github.com/Jutho/KrylovKit.jl/blob/1b175b7bd57a9535e26b738dbc7403ec30aee444/src/orthonormal.jl#L336), and then we index into these vectors (https://github.com/Jutho/KrylovKit.jl/blob/1b175b7bd57a9535e26b738dbc7403ec30aee444/src/orthonormal.jl#L342), which fails for non-`isbits` types.

Additionally, there really is no guarantee that `AbstractArray`s are efficiently indexable (or the indexing even means the same thing).
For example in MPSKit (where I ran into this issue), we have that `QuasiParticle` states subtype `AbstractVector`, because you can index into them by site, while we also have that they are elements of a vectorspace, for which we overload `VectorInterface`. While this design might be questionable, I would still expect KrylovKit to use the `VectorInterface` methods, instead of the `AbstractVector` methods.

[Edit] Actually, the reason it was going wrong is that in the `Multiline` tests, we used a `RecursiveVec` for the different lines, which I now changed for a regular `Vector`, thus changing this to `<:DenseArray` or `<:Array` also does not suffice.

**Comment by Jutho** [comment]
I am certainly happy to further restrict this to `DenseArray`, or maybe even just `Array`, as we want to exclude GPU arrays, and this condition is probably one of the only reasons why we depend on GPUArraysCore.jl. Furthermore, I am also happy to see `similar` replaced with `zerovector`.

**Comment by lkdvos** [comment]
I will try and have a look at it later this week. `<:DenseArray` actually does not really solve the problem, I think it would even have to be `<:DenseArray{<:Number}`, as the case I am having is `Vector{Quasiparticle}`, which is dense.
