### ISSUE TITLE
Recycling or Block Krylov

### ISSUE THREAD

**Issue by rveltz** [Jutho/KrylovKit.jl#16]
Hi,

I am not sure this is really an issue so feel free to close it.

I am using Newton - GMRES and I was wondering:

1. if there is a way to reuse the Krylov space from a previous iteration
2. Solve two linear systems Ax=rhs1, Ax = rhs2 in one pass?

Thank you for your help,

Besr regards

**Comment by Jutho** [comment]
Future requests are also welcome. Unfortunately, this is currently not possible.

1. Is this very useful? Typically you need several restarts no? One could put something together
2. Also, currently not really possible. You could accomplish something with `RecursiveVec`, i.e.
`linsolve(x->RecursiveVec(A*x[1],A*x[2]), RecursiveVec(rhs1,rhs2)),...)`
though that's probably not very efficient and not really what you're after.

**Comment by rveltz** [comment]
1. you are right...
2. if possible, do you know if it is faster (less iterations)?

**Comment by Jutho** [comment]
There do seem to be block variants of GMRES, but I don't know how they work.
