### ISSUE TITLE
mistake in mul!

### ISSUE THREAD

**Issue by rveltz** [Jutho/KrylovKit.jl#25]
Hi,

I am wondering if this [line](https://github.com/Jutho/KrylovKit.jl/blob/master/src/linsolve/gmres.jl#L116) is not a mistake. Indeed this corresponds to `mul!(w, α, v)` and not the definition in your docs: "mul!(w, v, α): out of place scalar multiplication; multiply vector v with scalar α and store the result in w".

**Comment by Jutho** [comment]
It took me some time to understand your question, but you mean that the order of the scalar and vector (2nd and 3rd argument) are interchanged with respect to what I write in the docs? Yes this probably needs to be changed to be compatible with the minimal implementation of vector type as written in the docs. Well caught. Julia's `AbstractArray`'s accept both forms of course.

**Comment by rveltz** [comment]
Yes that is what I mean! You can either change the docs or the code. I hope the others functions linsolve, eigsolve... respect this.

> Julia's AbstractArray's accept both forms of course.

I dont like AbstractArray's ;D

**Comment by Jutho** [comment]
Code update already in place on master, I will tag a new version if tests turn green.

**Comment by Jutho** [comment]
version 0.4.1 is up.

**Comment by rveltz** [comment]
Thank you!
