### ISSUE TITLE
geneigsolve not working properly

### ISSUE THREAD

**Issue by XiaoXiaoBaiCai** [Jutho/KrylovKit.jl#32]
Hi,

I was trying to use geneigsolve to solve a generalized eigenvalue problem. So I did some simple test, but it seems not working properly.

`A = rand(10,10);
A = A*A';
B = rand(10,10);
B = B*B';
geneigsolve(A,B,isposdef=true,ishermitian=true,issymmetric=true)
`
Then it gives me error: 

> ERROR: MethodError: objects of type Array{Float64,2} are not callable
Use square brackets [] for indexing an Array.

Is it a bug or did I do something wrong? Thanks very much.

Best regards
Wangwei

**Comment by Jutho** [comment]
Hi @XiaoXiaoBaiCai , you should put `A` and `B` together in a tuple as explained in the doc string. This is for consistency, you can also specify a single function `f` as first argument, for which `f(x)` should then return the result of `A*x` and `B*x` as first argument.

Note that if I run your test with the correct function call, `geneigsolve` errors out. In this case, it seems important to either set the tolerance to something bigger than `eps()`, or to explicitly specify `krylovdim = 10`. In a realistic use case, this should pose less of a problem.

**Comment by XiaoXiaoBaiCai** [comment]
Great, I manage to make things work for my code. Thanks very much.
