### ISSUE TITLE
issymmetric does not select Lanczos

### ISSUE THREAD

**Issue by rveltz** [Jutho/KrylovKit.jl#36]
Hi,

This MWE shows the problem, it uses Arnoldi.

Thanks for your help,

Bests,

PS: I am on KrylovKit v0.5.2 #master

```
N = 100
A = rand(TY,(N,N)) .- one(TY)/2
            A = (A+A')/2
Af = x->A*x
eigsolve(Af,rand(N),3; verbosity=2, issymmetric=true)	
```

**Comment by Jutho** [comment]
what is `TY` in this case? Is it a subtype of `Real` or of `Complex`?

**Comment by Jutho** [comment]
I changed some of the algorithm selection implementation and now uses inference to deduce the return type of the linear map. This fails for your case if you run it in the REPL, because `A` and `Af` are global variables and so inference leads to `Any`.

**Comment by Jutho** [comment]
However, I can see many people using this package in this way, so I should find a way to fix this.

**Comment by rveltz** [comment]
I have TY = Float64

**Comment by Jutho** [comment]
I think this issue is solved? Or maybe it depends on the Julia version.

**Comment by rveltz** [comment]
No,

In order to get Lanczos, I have to use `ishermitian=true` instead of `issymmrtuc=true`

**Comment by Jutho** [comment]
My apologies, I completely misread the error, and thought it was about something else I fixed today. You are correct, this is still an issue.

**Comment by Jutho** [comment]
I don't think this is still an issue, so I will close. Please reopen if necessary.
