### ISSUE TITLE
Finding repeated eigenvalues

### ISSUE THREAD

**Issue by mukherjeesoham** [Jutho/KrylovKit.jl#44]
Hi, is there a way to output all the eigenvectors corresponding to the same eigenvalue? Currently, I get 
```
Invariant subspace of dimension 1 (up to requested tolerance `tol = 1.0e-12`), which is smaller than the number of requested eigenvalues (i.e. `howmany == 2`); setting `howmany = 1'.
```
Is there a way around this, or is this a limitation of iterative methods in general?

Thanks

**Comment by Jutho** [comment]
Read my response to a similar question on Julia Discourse here:

https://discourse.julialang.org/t/possible-bug-in-krylovkit-eigsolve/55962/9

**Comment by mukherjeesoham** [comment]
Thanks for the pointer!
