### ISSUE TITLE
linsolve on CUDA has an issue

### ISSUE THREAD

**Issue by RibeiroAndre** [Jutho/KrylovKit.jl#45]
Hi!
Here's the issue:
```
using CUDA
using KrylovKit
linsolve(CuArray([1.0 2.0; 3.0 4.0]),CuArray([1.0,2.0]))
┌ Warning: Performing scalar operations on GPU arrays: This is very slow, consider disallowing these operations with `allowscalar(false)`
└ @ GPUArrays /pool/aerospace/Tools/julia-1.5.3/depot/packages/GPUArrays/WV76E/src/host/indexing.jl:43
```

This seems to fix it:
```
LinearAlgebra.mul!(x::CuArray{T,1},y::CuArray{T,1},α) where T = x .= α .* y;
```
Maybe something can be done about it in the code? I don't think this is an issue with LinearAlgebra as:
```
using LinearAlgebra
a=CuArray([1.0 2.0; 3.0 4.0]);
b=CuArray([1.0,2.0]);
c=CuArray([0.0,0.0]);
mul!(c,a,b)
```
works.

**Comment by Jutho** [comment]
Your second example is irrelevant right? There you are doing a matrix vector multiplication. What seems to be missing is a multiplication with a scalar using the `mul!` interface. This works for arrays in `LinearAlgebra`, but a method seems to be missing for `CuArrays`. I think this is a CUDA.jl issue.

**Comment by Jutho** [comment]
However, it would arguably be good to have dedicated tests for testing KrylovKit.jl - CUDA.jl interoperability.

**Comment by RibeiroAndre** [comment]
I thought the second example was showing that `mul!` works on `CuArrays` in general, so I don't know why KrylovKit requires making changes to `mul!` in order to work.
I can file this under CUDA.jl if you think that's more appropriate, but I don't know how to reproduce the issue without using KrylovKit.

**Comment by Jutho** [comment]
Because it's another method signature, you are illustrating
```
mul!(::CuArray, ::CuArray, ::CuArray)
```
the error is from
```
mul!(::CuArray, ::CuArray, ::Number)
```

**Comment by RibeiroAndre** [comment]
Ah, yes. Clearly. Thanks for pointing that out. I'll file a CUDA ticket and you can decide if you want to close this one.
Thanks!

**Comment by RibeiroAndre** [comment]
Works on Julia Version 1.6.2, CUDA toolkit 11.1.1.
