### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by rveltz** [Jutho/KrylovKit.jl#5]
Hi,

This is not really an issue but a suggestion...

Can you provide a way to monitor the run of the computations, like a verbose mode in `eigensolve`...

Thank you for your help and for your great package!

**Comment by Jutho** [comment]
That's a good suggestion; I will have to look into the new logging infrastructure of Julia. I expect this should be suitable for that purpose.

**Comment by Jutho** [comment]
Check out the new `verbosity` keyword in KrylovKit v0.2.0.

**Comment by rveltz** [comment]
Thank you!
