### ISSUE TITLE
eigsolve not working with howmany option

### ISSUE THREAD

**Issue by juliohm** [Jutho/KrylovKit.jl#62]
Am I doing something wrong?

```julia
julia> KrylovKit.eigsolve(rand(100,100), howmany=2)
ERROR: MethodError: no method matching eigselector(::Matrix{Float64}, ::Type{Float64}; howmany=2)
Closest candidates are:
  eigselector(::AbstractMatrix, ::Type; issymmetric, ishermitian, krylovdim, maxiter, tol, orth, eager, verbosity) at C:\Users\julio\.julia\packages\KrylovKit\kWdb6\src\eigsolve\eigsolve.jl:237 got unsupported keyword argument "howmany"
  eigselector(::Any, ::Type; issymmetric, ishermitian, krylovdim, maxiter, tol, orth, eager, verbosity) at C:\Users\julio\.julia\packages\KrylovKit\kWdb6\src\eigsolve\eigsolve.jl:205 got unsupported keyword argument "howmany"
Stacktrace:
 [1] kwerr(::NamedTuple{(:howmany,), Tuple{Int64}}, ::Function, ::Matrix{Float64}, ::Type)
   @ Base .\error.jl:165
 [2] eigsolve(f::Matrix{Float64}, x₀::Vector{Float64}, howmany::Int64, which::Symbol; kwargs::Base.Pairs{Symbol, Int64, Tuple{Symbol}, NamedTuple{(:howmany,), Tuple{Int64}}})
   @ KrylovKit C:\Users\julio\.julia\packages\KrylovKit\kWdb6\src\eigsolve\eigsolve.jl:184
 [3] eigsolve(A::Matrix{Float64}, howmany::Int64, which::Symbol, T::Type; kwargs::Base.Pairs{Symbol, Int64, Tuple{Symbol}, NamedTuple{(:howmany,), Tuple{Int64}}})
   @ KrylovKit C:\Users\julio\.julia\packages\KrylovKit\kWdb6\src\eigsolve\eigsolve.jl:176
 [4] top-level scope
   @ REPL[27]:1
```

**Comment by Jutho** [comment]
`howmany` is currently still a positional argument, not a keyword argument. I am considering to change this in a future (breaking) version

**Comment by juliohm** [comment]
I got confused with the docstring then. What about the xo argument? Is there a good recommendation? I understand that the howmany is the 3rd positional argument so we need to specify xo as well.

**Comment by Jutho** [comment]
Yes you need to specify x0, except when your operator is a matrix. In that case, I can generate a random vector. But KrylovKit works with arbitrary user types as vectors, and arbitrary functions as linear operators. I have no way to know what type of vector the user is using, and I cannot create random instances of it. So you have to specify one instance. Any random instance should be fine, as long as it is not the zero vector. If it is already close to being an eigenvector, than convergence will be faster.

**Comment by juliohm** [comment]
It would be great to make these keyword arguments indeed. Also, the return type of the eigenvectors could be a simple matrix as with other linear algebra packages maybe? I tried to port some code from ArnoldMethod.jl to KrylovKit.jl without success.

Marking the issue as solved.

**Comment by Jutho** [comment]
I think you miss the point of this package. Vectors can be any user type that satisfy a minimal interface. In particular; they don't have to be `AbstractVector` or `Vector`. As such, concatenating them into a matrix doesn't make sense; a list of eigenvectors is the only sensible return type. If you don't need this functionality and your vectors are simple `Vector`s, then this package still works, but I don't think it gains you much over Arpack.jl or ArnoldiMethod.jl, and indeed, because of this more general approach, some behaviour might be somewhat different.

**Comment by juliohm** [comment]
I fully get it, it is really nice that the entire interface here works with
general vector spaces. I'm wondering if in the case of Vector it would make
sense to provide an option or wrapper function that returns matrices of
coordinates. Just because it is handy sometimes.

Em sex., 28 de out. de 2022 16:31, Jutho ***@***.***>
escreveu:

**Comment by Jutho** [comment]
It's a simple matter of doing `hcat(vecs...)` to get the corresponding matrix in that case.

**Comment by juliohm** [comment]
Yep, maybe it doesn't make sense to include here. Alternatively you could
add a new Krylov.eigs or something that mimics the LinearAlgebra output

Em sex., 28 de out. de 2022 16:43, Jutho ***@***.***>
escreveu:
