### ISSUE TITLE
Standard evp (non-symm, real matrix): too many iterations

### ISSUE THREAD

**Issue by PetrKryslUCSD** [Jutho/KrylovKit.jl#75]
https://discourse.julialang.org/t/julia-is-slower-than-matlab-when-it-comes-to-matrix-diagonalization/108658/36

Matlab apparently takes 7; KrylovKit 1600!

**Comment by Jutho** [comment]
I tried browsing through the thread to recover the matrices involved, but did not easily find it. Can you very explicitly tell me where to find or how to create the matrix/function that implements the linear operator that needs to be diagonalised?

**Comment by PetrKryslUCSD** [comment]
False alarm. Sorry. I should have solved for the largest eigenvalues of the inverse.
