### ISSUE TITLE
citation

### ISSUE THREAD

**Issue by bzhangcw** [Jutho/KrylovKit.jl#77]
Hi, I'm using your package in a journal paper, so I wonder if you have a Bibtex entry for a citation?

**Comment by Jutho** [comment]
Hi @bzhangcw, thanks for this question and for citing this package. Unfortunately, for KrylovKit.jl, there is no official citation yet. For some of my other packages I have registered a DOI via Zenedo, but this is not yet the case for KrylovKit. I do hope to invest some time in this package soon, as there are a couple of necessary updates in the pipeline, and this is a good reminder that I should then also register it at Zenedo. But for now, I would suggest to just cite it via its URL.

**Comment by bachrathyd** [comment]
Same problem here! ;-)
