### ISSUE TITLE
WARNING: using ChainRulesCore.add!! in module KrylovKit conflicts with an existing identifier.

### ISSUE THREAD

**Issue by atbug** [Jutho/KrylovKit.jl#82]
This is the warning I get when `using KrylovKit` with `julia --compiled-modules=no`.

**Comment by lkdvos** [comment]
Hi atbug, I think for now this warning is mostly harmless (unless you have any concrete issues?). I am working on moving the AD rules to a package extension, which should fix this. I'll link that PR once it is ready :)

**Comment by atbug** [comment]
Thank you. I don't have any concrete issues. I am just a little bit allergic to warnings.

**Comment by lkdvos** [comment]
I totally understand, I get that feeling too sometimes 😊
