### ISSUE TITLE
Missing eigenvalues

### ISSUE THREAD

**Issue by ttx002000** [Jutho/KrylovKit.jl#90]
I have the some big sparse matrix to be diagonalized. When compared with the Arpack results, it seems that there are multiple eigenvalues missing in the degenerate subspace using Krylovkit. 

The only change I make in my code is changing from
>MB_spectrum,ζ,info=eigsolve(sparse(matrix_index1,matrix_index2,matrix_value,length(state_can),length(state_can)),25,:SR)
   
to 
> MB_spectrum,ζ=eigs(sparse(matrix_index1,matrix_index2,matrix_value,length(state_can),length(state_can)), nev=25,which=:SR)
    
The second one use Arpack method, and here are the eigenvalues it obtained (the first 15 of it)
![image](https://github.com/Jutho/KrylovKit.jl/assets/84668553/b8f42568-b956-490c-a72f-d0d025bf9f45)

The first one use KrylovKit method, and here are the eigenvalues it obtained (the first 15 of it)
![image](https://github.com/Jutho/KrylovKit.jl/assets/84668553/69fc07fb-ed2e-4598-84de-78c005bb3350)

It seems that Krylovkit missed 2 of the 6 eigenvalues at 3.212527.

**Comment by lkdvos** [comment]
Hi ttx,
Note that really, Krylov methods are not super well-suited for degenerate subspaces. (See for example the note in [the docstring](https://jutho.github.io/KrylovKit.jl/latest/man/eig/#KrylovKit.eigsolve))
This being said, often the Krylov methods still work, but you typically have to play around a bit with the parameters. If you make the `tol` more strict, or the `krylovdim` a bit larger, it might then find these other eigenvectors as well.

**Comment by ttx002000** [comment]
Hi, I haven't got a chance to do that, but please go ahead c
